Metrics/LineLength:
  Max: 120

AllCops:
  Exclude:
    - spec/spec_helper.rb
  Include:
    - '**/*.ru'

Documentation:
  Exclude:
    - spec/*_spec.rb

Style/TrivialAccessors:
  Exclude:
    - '**/*dsl*.rb'

